"""Standard identity error envelope and exception handling (SRS §18).

Every identity API returns, on failure:

    {"success": false, "error": {"code": "...", "message": "..."}, "request_id": "..."}

Handlers are registered only for identity errors, so the rest of the platform's
error format is unchanged.
"""

from __future__ import annotations

from datetime import datetime, timezone

from fastapi import FastAPI, Request, status
from fastapi.responses import JSONResponse

from app.identity.security.passwords import PasswordPolicyError


class ErrorCode:
    """Stable, machine-readable identity error codes."""

    USER_NOT_FOUND = "USER_NOT_FOUND"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
    DEPARTMENT_NOT_FOUND = "DEPARTMENT_NOT_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    IDENTITY_NOT_FOUND = "IDENTITY_NOT_FOUND"
    AGENT_IDENTITY_NOT_FOUND = "AGENT_IDENTITY_NOT_FOUND"
    SERVICE_ACCOUNT_NOT_FOUND = "SERVICE_ACCOUNT_NOT_FOUND"
    EXTERNAL_CLIENT_NOT_FOUND = "EXTERNAL_CLIENT_NOT_FOUND"
    INVALID_LIFECYCLE_TRANSITION = "INVALID_LIFECYCLE_TRANSITION"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    CONFLICT = "CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    # Phase 4.2.1 authentication error codes (SRS §25).
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    REFRESH_TOKEN_REUSED = "REFRESH_TOKEN_REUSED"
    IDENTITY_DISABLED = "IDENTITY_DISABLED"
    IDENTITY_SUSPENDED = "IDENTITY_SUSPENDED"
    SESSION_REVOKED = "SESSION_REVOKED"
    API_KEY_INVALID = "API_KEY_INVALID"
    API_KEY_EXPIRED = "API_KEY_EXPIRED"
    MFA_REQUIRED = "MFA_REQUIRED"
    INSUFFICIENT_SCOPE = "INSUFFICIENT_SCOPE"
    # Human authentication (SRS 4.2.2.1 §21).
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    PASSWORD_EXPIRED = "PASSWORD_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    REFRESH_FAILED = "REFRESH_FAILED"
    # Session lifecycle (SRS 4.2.2.2 §27).
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_IDLE_TIMEOUT = "SESSION_IDLE_TIMEOUT"
    SESSION_SUSPICIOUS = "SESSION_SUSPICIOUS"
    DEVICE_BLOCKED = "DEVICE_BLOCKED"
    DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
    TOKEN_REUSE = "TOKEN_REUSE"
    TOO_MANY_SESSIONS = "TOO_MANY_SESSIONS"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    # Registration & invitations (4.2.2.3.1 §18).
    INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND"
    INVITATION_EXPIRED = "INVITATION_EXPIRED"
    INVITATION_ALREADY_USED = "INVITATION_ALREADY_USED"
    INVITATION_CANCELLED = "INVITATION_CANCELLED"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN"
    VERIFICATION_TOKEN_EXPIRED = "VERIFICATION_TOKEN_EXPIRED"
    REGISTRATION_DISABLED = "REGISTRATION_DISABLED"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    ACCOUNT_PENDING_APPROVAL = "ACCOUNT_PENDING_APPROVAL"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    # Credential management (4.2.2.3.2 §26). PASSWORD_EXPIRED already exists above.
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
    PASSWORD_REUSED = "PASSWORD_REUSED"
    PASSWORD_HISTORY_VIOLATION = "PASSWORD_HISTORY_VIOLATION"
    INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD"
    TEMP_PASSWORD_EXPIRED = "TEMP_PASSWORD_EXPIRED"
    PASSWORD_POLICY_FAILED = "PASSWORD_POLICY_FAILED"
    FIRST_LOGIN_CHANGE_REQUIRED = "FIRST_LOGIN_CHANGE_REQUIRED"
    PASSWORD_MIN_AGE = "PASSWORD_MIN_AGE"
    # Password reset & recovery (4.2.2.3.3 §25).
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"
    RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED"
    RESET_TOKEN_USED = "RESET_TOKEN_USED"
    EMAIL_VERIFICATION_EXPIRED = "EMAIL_VERIFICATION_EXPIRED"
    PASSWORD_RESET_DISABLED = "PASSWORD_RESET_DISABLED"
    INVALID_RECOVERY_REQUEST = "INVALID_RECOVERY_REQUEST"
    EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE"
    # Account protection & risk-based authentication (4.2.2.3.4 §32).
    # ACCOUNT_LOCKED already exists above (4.2.2.1). These are new.
    LOGIN_BLOCKED = "LOGIN_BLOCKED"
    RISK_CHALLENGE_REQUIRED = "RISK_CHALLENGE_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    IP_BLOCKED = "IP_BLOCKED"
    SECURITY_REVIEW_REQUIRED = "SECURITY_REVIEW_REQUIRED"
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS"
    PROTECTION_RULE_DENIED = "PROTECTION_RULE_DENIED"
    ACCOUNT_LOCK_NOT_FOUND = "ACCOUNT_LOCK_NOT_FOUND"
    PROTECTION_RULE_NOT_FOUND = "PROTECTION_RULE_NOT_FOUND"
    BLOCKED_IP_NOT_FOUND = "BLOCKED_IP_NOT_FOUND"
    # Enterprise RBAC foundation (Phase 4.3.1 §24). ROLE_NOT_FOUND already exists above.
    ROLE_ALREADY_EXISTS = "ROLE_ALREADY_EXISTS"
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND"
    PERMISSION_ALREADY_EXISTS = "PERMISSION_ALREADY_EXISTS"
    INVALID_PERMISSION_NAME = "INVALID_PERMISSION_NAME"
    ROLE_HAS_ASSIGNMENTS = "ROLE_HAS_ASSIGNMENTS"
    CIRCULAR_ROLE_HIERARCHY = "CIRCULAR_ROLE_HIERARCHY"
    INVALID_SCOPE = "INVALID_SCOPE"
    SYSTEM_ROLE_PROTECTED = "SYSTEM_ROLE_PROTECTED"
    ROLE_ASSIGNMENT_NOT_FOUND = "ROLE_ASSIGNMENT_NOT_FOUND"
    PERMISSION_GROUP_NOT_FOUND = "PERMISSION_GROUP_NOT_FOUND"
    ROLE_HIERARCHY_EDGE_NOT_FOUND = "ROLE_HIERARCHY_EDGE_NOT_FOUND"
    # Permission engine (Phase 4.3.2 §28). PERMISSION_DENIED already exists above.
    ROLE_NOT_ASSIGNED = "ROLE_NOT_ASSIGNED"
    RESOURCE_FORBIDDEN = "RESOURCE_FORBIDDEN"
    EXPLICIT_DENY = "EXPLICIT_DENY"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    PERMISSION_CACHE_MISS = "PERMISSION_CACHE_MISS"
    # Organization hierarchy (Phase 4.3.3 §19). ORGANIZATION_NOT_FOUND /
    # DEPARTMENT_NOT_FOUND already exist above.
    BUSINESS_UNIT_NOT_FOUND = "BUSINESS_UNIT_NOT_FOUND"
    TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    RESOURCE_OWNERSHIP_NOT_FOUND = "RESOURCE_OWNERSHIP_NOT_FOUND"
    CROSS_ORG_FORBIDDEN = "CROSS_ORG_FORBIDDEN"
    ENTITY_HAS_CHILDREN = "ENTITY_HAS_CHILDREN"
    DELEGATION_EXCEEDS_AUTHORITY = "DELEGATION_EXCEEDS_AUTHORITY"
    DELEGATION_NOT_FOUND = "DELEGATION_NOT_FOUND"
    HIERARCHY_INTEGRITY_ERROR = "HIERARCHY_INTEGRITY_ERROR"
    # Resource-based authorization (Phase 4.3.4 §24).
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_OWNER_REQUIRED = "RESOURCE_OWNER_REQUIRED"
    ACL_ENTRY_NOT_FOUND = "ACL_ENTRY_NOT_FOUND"
    RESOURCE_NOT_SHARED = "RESOURCE_NOT_SHARED"
    DELEGATION_EXPIRED = "DELEGATION_EXPIRED"
    OWNER_TRANSFER_NOT_ALLOWED = "OWNER_TRANSFER_NOT_ALLOWED"
    RESOURCE_POLICY_DENIED = "RESOURCE_POLICY_DENIED"
    CROSS_ORGANIZATION_ACCESS_DENIED = "CROSS_ORGANIZATION_ACCESS_DENIED"
    RESOURCE_ACCESS_DENIED = "RESOURCE_ACCESS_DENIED"
    # ABAC engine (Phase 4.3.5 §39).
    ABAC_POLICY_NOT_FOUND = "ABAC_POLICY_NOT_FOUND"
    ABAC_POLICY_INVALID = "ABAC_POLICY_INVALID"
    ABAC_ATTRIBUTE_NOT_FOUND = "ABAC_ATTRIBUTE_NOT_FOUND"
    ABAC_ATTRIBUTE_TYPE_MISMATCH = "ABAC_ATTRIBUTE_TYPE_MISMATCH"
    ABAC_OPERATOR_NOT_SUPPORTED = "ABAC_OPERATOR_NOT_SUPPORTED"
    ABAC_CONDITION_INVALID = "ABAC_CONDITION_INVALID"
    ABAC_EFFECT_INVALID = "ABAC_EFFECT_INVALID"
    ABAC_OBLIGATION_INVALID = "ABAC_OBLIGATION_INVALID"
    ABAC_POLICY_CONFLICT = "ABAC_POLICY_CONFLICT"
    ABAC_SCOPE_INVALID = "ABAC_SCOPE_INVALID"
    ABAC_EVALUATION_FAILED = "ABAC_EVALUATION_FAILED"
    ABAC_REQUIRED_ATTRIBUTE_MISSING = "ABAC_REQUIRED_ATTRIBUTE_MISSING"
    ABAC_POLICY_PUBLISH_DENIED = "ABAC_POLICY_PUBLISH_DENIED"
    # Authorization middleware (Phase 4.3.6 §25). AUTHENTICATION_FAILED,
    # SESSION_EXPIRED, PERMISSION_DENIED, RESOURCE_FORBIDDEN, MFA_REQUIRED and
    # ABAC_EVALUATION_FAILED already exist above.
    ABAC_DENIED = "ABAC_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    JUSTIFICATION_REQUIRED = "JUSTIFICATION_REQUIRED"
    # Identity Governance & Administration (Phase 4.3.8 §24).
    SOD_RULE_NOT_FOUND = "SOD_RULE_NOT_FOUND"
    GOVERNANCE_FINDING_NOT_FOUND = "GOVERNANCE_FINDING_NOT_FOUND"
    REMEDIATION_ACTION_NOT_FOUND = "REMEDIATION_ACTION_NOT_FOUND"
    REMEDIATION_ALREADY_EXECUTED = "REMEDIATION_ALREADY_EXECUTED"
    PRIVILEGED_REVIEW_NOT_FOUND = "PRIVILEGED_REVIEW_NOT_FOUND"
    COMPLIANCE_REPORT_NOT_FOUND = "COMPLIANCE_REPORT_NOT_FOUND"
    SOD_RULE_NOT_ACTIVE = "SOD_RULE_NOT_ACTIVE"
    CERTIFICATION_DECISION_IMMUTABLE = "CERTIFICATION_DECISION_IMMUTABLE"
    # Agent Runtime & Lifecycle Management (Phase 5.0 §77).
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_NOT_ACTIVE = "AGENT_NOT_ACTIVE"
    AGENT_SUSPENDED = "AGENT_SUSPENDED"
    AGENT_VERSION_NOT_FOUND = "AGENT_VERSION_NOT_FOUND"
    AGENT_VERSION_NOT_PUBLISHED = "AGENT_VERSION_NOT_PUBLISHED"
    AGENT_VERSION_REVOKED = "AGENT_VERSION_REVOKED"
    AGENT_VERSION_IMMUTABLE = "AGENT_VERSION_IMMUTABLE"
    DEPLOYMENT_NOT_FOUND = "DEPLOYMENT_NOT_FOUND"
    DEPLOYMENT_NOT_ACTIVE = "DEPLOYMENT_NOT_ACTIVE"
    DEPLOYMENT_UNHEALTHY = "DEPLOYMENT_UNHEALTHY"
    EXECUTION_NOT_FOUND = "EXECUTION_NOT_FOUND"
    EXECUTION_ALREADY_COMPLETED = "EXECUTION_ALREADY_COMPLETED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
    EXECUTION_TIMED_OUT = "EXECUTION_TIMED_OUT"
    EXECUTION_LIMIT_EXCEEDED = "EXECUTION_LIMIT_EXCEEDED"
    INVALID_EXECUTION_TRANSITION = "INVALID_EXECUTION_TRANSITION"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
    CAPABILITY_NOT_APPROVED = "CAPABILITY_NOT_APPROVED"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_NOT_ASSIGNED = "TOOL_NOT_ASSIGNED"
    TOOL_ACTION_NOT_ALLOWED = "TOOL_ACTION_NOT_ALLOWED"
    TOOL_CONSTRAINT_VIOLATION = "TOOL_CONSTRAINT_VIOLATION"
    MODEL_NOT_APPROVED = "MODEL_NOT_APPROVED"
    MODEL_PROVIDER_UNAVAILABLE = "MODEL_PROVIDER_UNAVAILABLE"
    RUNTIME_POLICY_DENIED = "RUNTIME_POLICY_DENIED"
    RUNTIME_APPROVAL_REQUIRED = "RUNTIME_APPROVAL_REQUIRED"
    RUNTIME_APPROVAL_NOT_FOUND = "RUNTIME_APPROVAL_NOT_FOUND"
    RUNTIME_BUDGET_EXCEEDED = "RUNTIME_BUDGET_EXCEEDED"
    RUNTIME_RATE_LIMITED = "RUNTIME_RATE_LIMITED"
    RUNTIME_QUEUE_FULL = "RUNTIME_QUEUE_FULL"
    WORKER_UNAVAILABLE = "WORKER_UNAVAILABLE"
    ROLLBACK_NOT_AVAILABLE = "ROLLBACK_NOT_AVAILABLE"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    SECRET_REFERENCE_INVALID = "SECRET_REFERENCE_INVALID"
    # Enterprise Agent Registry (Phase 5.1 §68).
    AGENT_ALREADY_EXISTS = "AGENT_ALREADY_EXISTS"
    AGENT_SLUG_CONFLICT = "AGENT_SLUG_CONFLICT"
    AGENT_EXTERNAL_REFERENCE_CONFLICT = "AGENT_EXTERNAL_REFERENCE_CONFLICT"
    AGENT_INVALID_STATUS = "AGENT_INVALID_STATUS"
    AGENT_TRANSITION_NOT_ALLOWED = "AGENT_TRANSITION_NOT_ALLOWED"
    AGENT_NOT_EDITABLE = "AGENT_NOT_EDITABLE"
    AGENT_VALIDATION_FAILED = "AGENT_VALIDATION_FAILED"
    AGENT_VALIDATION_IN_PROGRESS = "AGENT_VALIDATION_IN_PROGRESS"
    AGENT_APPROVAL_REQUIRED = "AGENT_APPROVAL_REQUIRED"
    AGENT_ACTIVATION_BLOCKED = "AGENT_ACTIVATION_BLOCKED"
    AGENT_OWNER_REQUIRED = "AGENT_OWNER_REQUIRED"
    AGENT_OWNER_INVALID = "AGENT_OWNER_INVALID"
    AGENT_OWNER_SCOPE_MISMATCH = "AGENT_OWNER_SCOPE_MISMATCH"
    AGENT_IDENTITY_REQUIRED = "AGENT_IDENTITY_REQUIRED"
    AGENT_IDENTITY_INVALID = "AGENT_IDENTITY_INVALID"
    AGENT_IDENTITY_SCOPE_MISMATCH = "AGENT_IDENTITY_SCOPE_MISMATCH"
    AGENT_IDENTITY_ALREADY_ASSIGNED = "AGENT_IDENTITY_ALREADY_ASSIGNED"
    AGENT_DEFINITION_REQUIRED = "AGENT_DEFINITION_REQUIRED"
    AGENT_ENTRYPOINT_INVALID = "AGENT_ENTRYPOINT_INVALID"
    AGENT_INPUT_SCHEMA_INVALID = "AGENT_INPUT_SCHEMA_INVALID"
    AGENT_OUTPUT_SCHEMA_INVALID = "AGENT_OUTPUT_SCHEMA_INVALID"
    AGENT_CONFIGURATION_SCHEMA_INVALID = "AGENT_CONFIGURATION_SCHEMA_INVALID"
    AGENT_RISK_CLASSIFICATION_INVALID = "AGENT_RISK_CLASSIFICATION_INVALID"
    AGENT_DUPLICATE_CONFIRMED = "AGENT_DUPLICATE_CONFIRMED"
    AGENT_DUPLICATE_REVIEW_REQUIRED = "AGENT_DUPLICATE_REVIEW_REQUIRED"
    AGENT_CONCURRENT_MODIFICATION = "AGENT_CONCURRENT_MODIFICATION"
    AGENT_IMPORT_INVALID = "AGENT_IMPORT_INVALID"
    AGENT_IMPORT_PARTIAL_FAILURE = "AGENT_IMPORT_PARTIAL_FAILURE"
    AGENT_EXPORT_DENIED = "AGENT_EXPORT_DENIED"
    # Enterprise Versioning & Release Management (Phase 5.2 Part 1).
    AGENT_VERSION_INVALID_SEMVER = "AGENT_VERSION_INVALID_SEMVER"
    AGENT_VERSION_SEMVER_NOT_INCREASING = "AGENT_VERSION_SEMVER_NOT_INCREASING"
    AGENT_VERSION_SNAPSHOT_LOCKED = "AGENT_VERSION_SNAPSHOT_LOCKED"
    AGENT_VERSION_ROLLBACK_TARGET_INVALID = "AGENT_VERSION_ROLLBACK_TARGET_INVALID"
    AGENT_RELEASE_CHANNEL_NOT_FOUND = "AGENT_RELEASE_CHANNEL_NOT_FOUND"
    # Compatibility & Breaking-Change Detection (Phase 5.2.6).
    COMPATIBILITY_BASELINE_NOT_FOUND = "COMPATIBILITY_BASELINE_NOT_FOUND"
    COMPATIBILITY_SNAPSHOT_UNAVAILABLE = "COMPATIBILITY_SNAPSHOT_UNAVAILABLE"


# Map error codes → HTTP status.
_STATUS: dict[str, int] = {
    ErrorCode.USER_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.ROLE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.ORGANIZATION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.DEPARTMENT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.SESSION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.IDENTITY_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.AGENT_IDENTITY_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.SERVICE_ACCOUNT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.EXTERNAL_CLIENT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.INVALID_LIFECYCLE_TRANSITION: status.HTTP_409_CONFLICT,
    ErrorCode.CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.VALIDATION_ERROR: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.PERMISSION_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.AUTHENTICATION_FAILED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.INTERNAL_ERROR: status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Authentication (SRS §25).
    ErrorCode.INVALID_CREDENTIALS: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.TOKEN_EXPIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.TOKEN_REVOKED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.REFRESH_TOKEN_REUSED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.IDENTITY_DISABLED: status.HTTP_403_FORBIDDEN,
    ErrorCode.IDENTITY_SUSPENDED: status.HTTP_403_FORBIDDEN,
    ErrorCode.SESSION_REVOKED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.API_KEY_INVALID: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.API_KEY_EXPIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.MFA_REQUIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.INSUFFICIENT_SCOPE: status.HTTP_403_FORBIDDEN,
    # Human authentication (SRS 4.2.2.1 §21).
    ErrorCode.ACCOUNT_LOCKED: status.HTTP_423_LOCKED,
    ErrorCode.ACCOUNT_DISABLED: status.HTTP_403_FORBIDDEN,
    ErrorCode.PASSWORD_EXPIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.TOKEN_INVALID: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.REFRESH_FAILED: status.HTTP_401_UNAUTHORIZED,
    # Session lifecycle (SRS 4.2.2.2 §27).
    ErrorCode.SESSION_EXPIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.SESSION_IDLE_TIMEOUT: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.SESSION_SUSPICIOUS: status.HTTP_401_UNAUTHORIZED,
    # A blocked device is an authorization decision about the *device*, not the
    # credential — the password was correct. 403, not 401.
    ErrorCode.DEVICE_BLOCKED: status.HTTP_403_FORBIDDEN,
    ErrorCode.DEVICE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.TOKEN_REUSE: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.TOO_MANY_SESSIONS: status.HTTP_409_CONFLICT,
    ErrorCode.INVALID_REFRESH_TOKEN: status.HTTP_401_UNAUTHORIZED,
    # Registration & invitations (4.2.2.3.1 §18).
    ErrorCode.INVITATION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    # 410 Gone, not 404: the link *was* valid. The user needs to be told to ask for
    # a new one, not that they mistyped a URL.
    ErrorCode.INVITATION_EXPIRED: status.HTTP_410_GONE,
    ErrorCode.INVITATION_ALREADY_USED: status.HTTP_410_GONE,
    ErrorCode.INVITATION_CANCELLED: status.HTTP_410_GONE,
    ErrorCode.EMAIL_ALREADY_VERIFIED: status.HTTP_409_CONFLICT,
    ErrorCode.INVALID_VERIFICATION_TOKEN: status.HTTP_400_BAD_REQUEST,
    ErrorCode.VERIFICATION_TOKEN_EXPIRED: status.HTTP_410_GONE,
    ErrorCode.REGISTRATION_DISABLED: status.HTTP_403_FORBIDDEN,
    ErrorCode.USER_ALREADY_EXISTS: status.HTTP_409_CONFLICT,
    # The credential was correct; the account is simply not usable yet. 403, not
    # 401 — re-entering the password cannot help.
    ErrorCode.EMAIL_NOT_VERIFIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.ACCOUNT_PENDING_APPROVAL: status.HTTP_403_FORBIDDEN,
    ErrorCode.RATE_LIMIT_EXCEEDED: status.HTTP_429_TOO_MANY_REQUESTS,
    # Credential management (4.2.2.3.2 §26). Policy failures are client input
    # errors (422); a wrong current password is an auth failure (401).
    ErrorCode.PASSWORD_TOO_WEAK: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.PASSWORD_REUSED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.PASSWORD_HISTORY_VIOLATION: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_CURRENT_PASSWORD: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.TEMP_PASSWORD_EXPIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.PASSWORD_POLICY_FAILED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.FIRST_LOGIN_CHANGE_REQUIRED: status.HTTP_403_FORBIDDEN,
    ErrorCode.PASSWORD_MIN_AGE: status.HTTP_409_CONFLICT,
    # Password reset & recovery (4.2.2.3.3 §25).
    # A dead reset link *was* valid: 410 Gone, not 404 — tell the user to request a
    # new one, the same discipline as invitation/verification links.
    ErrorCode.RESET_TOKEN_INVALID: status.HTTP_400_BAD_REQUEST,
    ErrorCode.RESET_TOKEN_EXPIRED: status.HTTP_410_GONE,
    ErrorCode.RESET_TOKEN_USED: status.HTTP_410_GONE,
    ErrorCode.EMAIL_VERIFICATION_EXPIRED: status.HTTP_410_GONE,
    ErrorCode.PASSWORD_RESET_DISABLED: status.HTTP_403_FORBIDDEN,
    ErrorCode.INVALID_RECOVERY_REQUEST: status.HTTP_400_BAD_REQUEST,
    ErrorCode.EMAIL_ALREADY_IN_USE: status.HTTP_409_CONFLICT,
    # Account protection (4.2.2.3.4 §32). A blocked/too-many/challenge verdict is a
    # 429 or 403 — never a detailed leak of *why* (§33).
    ErrorCode.LOGIN_BLOCKED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RISK_CHALLENGE_REQUIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.CAPTCHA_REQUIRED: status.HTTP_401_UNAUTHORIZED,
    ErrorCode.IP_BLOCKED: status.HTTP_403_FORBIDDEN,
    ErrorCode.SECURITY_REVIEW_REQUIRED: status.HTTP_403_FORBIDDEN,
    ErrorCode.TOO_MANY_ATTEMPTS: status.HTTP_429_TOO_MANY_REQUESTS,
    ErrorCode.PROTECTION_RULE_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.ACCOUNT_LOCK_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.PROTECTION_RULE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.BLOCKED_IP_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    # Enterprise RBAC foundation (Phase 4.3.1 §24).
    ErrorCode.ROLE_ALREADY_EXISTS: status.HTTP_409_CONFLICT,
    ErrorCode.PERMISSION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.PERMISSION_ALREADY_EXISTS: status.HTTP_409_CONFLICT,
    ErrorCode.INVALID_PERMISSION_NAME: status.HTTP_422_UNPROCESSABLE_ENTITY,
    # A role with live assignments cannot be deleted (§8, §25): 409, not 403.
    ErrorCode.ROLE_HAS_ASSIGNMENTS: status.HTTP_409_CONFLICT,
    ErrorCode.CIRCULAR_ROLE_HIERARCHY: status.HTTP_409_CONFLICT,
    ErrorCode.INVALID_SCOPE: status.HTTP_422_UNPROCESSABLE_ENTITY,
    # System roles are protected from edit/delete (§25): 403.
    ErrorCode.SYSTEM_ROLE_PROTECTED: status.HTTP_403_FORBIDDEN,
    ErrorCode.ROLE_ASSIGNMENT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.PERMISSION_GROUP_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.ROLE_HIERARCHY_EDGE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    # Permission engine (Phase 4.3.2 §28) — all authorization denials are 403.
    ErrorCode.ROLE_NOT_ASSIGNED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RESOURCE_FORBIDDEN: status.HTTP_403_FORBIDDEN,
    ErrorCode.EXPLICIT_DENY: status.HTTP_403_FORBIDDEN,
    ErrorCode.AUTHORIZATION_FAILED: status.HTTP_403_FORBIDDEN,
    ErrorCode.PERMISSION_CACHE_MISS: status.HTTP_500_INTERNAL_SERVER_ERROR,
    # Organization hierarchy (Phase 4.3.3 §19).
    ErrorCode.BUSINESS_UNIT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.TEAM_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.PROJECT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.RESOURCE_OWNERSHIP_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.CROSS_ORG_FORBIDDEN: status.HTTP_403_FORBIDDEN,
    # A parent with children cannot be deleted until they are handled/reassigned (§19).
    ErrorCode.ENTITY_HAS_CHILDREN: status.HTTP_409_CONFLICT,
    ErrorCode.DELEGATION_EXCEEDS_AUTHORITY: status.HTTP_403_FORBIDDEN,
    ErrorCode.DELEGATION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.HIERARCHY_INTEGRITY_ERROR: status.HTTP_409_CONFLICT,
    # Resource-based authorization (Phase 4.3.4 §24).
    ErrorCode.RESOURCE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.RESOURCE_OWNER_REQUIRED: status.HTTP_403_FORBIDDEN,
    ErrorCode.ACL_ENTRY_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.RESOURCE_NOT_SHARED: status.HTTP_404_NOT_FOUND,
    ErrorCode.DELEGATION_EXPIRED: status.HTTP_410_GONE,
    ErrorCode.OWNER_TRANSFER_NOT_ALLOWED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RESOURCE_POLICY_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.CROSS_ORGANIZATION_ACCESS_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RESOURCE_ACCESS_DENIED: status.HTTP_403_FORBIDDEN,
    # ABAC engine (Phase 4.3.5 §39).
    ErrorCode.ABAC_POLICY_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.ABAC_POLICY_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_ATTRIBUTE_NOT_FOUND: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_ATTRIBUTE_TYPE_MISMATCH: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_OPERATOR_NOT_SUPPORTED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_CONDITION_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_EFFECT_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_OBLIGATION_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_POLICY_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.ABAC_SCOPE_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_EVALUATION_FAILED: status.HTTP_500_INTERNAL_SERVER_ERROR,
    ErrorCode.ABAC_REQUIRED_ATTRIBUTE_MISSING: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.ABAC_POLICY_PUBLISH_DENIED: status.HTTP_403_FORBIDDEN,
    # Authorization middleware (Phase 4.3.6 §25).
    ErrorCode.ABAC_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.APPROVAL_REQUIRED: status.HTTP_403_FORBIDDEN,
    ErrorCode.JUSTIFICATION_REQUIRED: status.HTTP_403_FORBIDDEN,
    # Identity Governance & Administration (Phase 4.3.8 §24).
    ErrorCode.SOD_RULE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.GOVERNANCE_FINDING_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.REMEDIATION_ACTION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.REMEDIATION_ALREADY_EXECUTED: status.HTTP_409_CONFLICT,
    ErrorCode.PRIVILEGED_REVIEW_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.COMPLIANCE_REPORT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.SOD_RULE_NOT_ACTIVE: status.HTTP_409_CONFLICT,
    # Certification decisions are immutable after the campaign completes (§24): 409.
    ErrorCode.CERTIFICATION_DECISION_IMMUTABLE: status.HTTP_409_CONFLICT,
    # Agent Runtime & Lifecycle Management (Phase 5.0 §77).
    ErrorCode.AGENT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.AGENT_NOT_ACTIVE: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_SUSPENDED: status.HTTP_403_FORBIDDEN,
    ErrorCode.AGENT_VERSION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.AGENT_VERSION_NOT_PUBLISHED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_VERSION_REVOKED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_VERSION_IMMUTABLE: status.HTTP_409_CONFLICT,
    ErrorCode.DEPLOYMENT_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.DEPLOYMENT_NOT_ACTIVE: status.HTTP_409_CONFLICT,
    ErrorCode.DEPLOYMENT_UNHEALTHY: status.HTTP_409_CONFLICT,
    ErrorCode.EXECUTION_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.EXECUTION_ALREADY_COMPLETED: status.HTTP_409_CONFLICT,
    ErrorCode.EXECUTION_CANCELLED: status.HTTP_409_CONFLICT,
    ErrorCode.EXECUTION_TIMED_OUT: status.HTTP_504_GATEWAY_TIMEOUT,
    ErrorCode.EXECUTION_LIMIT_EXCEEDED: status.HTTP_429_TOO_MANY_REQUESTS,
    ErrorCode.INVALID_EXECUTION_TRANSITION: status.HTTP_409_CONFLICT,
    ErrorCode.IDEMPOTENCY_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.CAPABILITY_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.CAPABILITY_NOT_APPROVED: status.HTTP_403_FORBIDDEN,
    ErrorCode.TOOL_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.TOOL_NOT_ASSIGNED: status.HTTP_403_FORBIDDEN,
    ErrorCode.TOOL_ACTION_NOT_ALLOWED: status.HTTP_403_FORBIDDEN,
    ErrorCode.TOOL_CONSTRAINT_VIOLATION: status.HTTP_403_FORBIDDEN,
    ErrorCode.MODEL_NOT_APPROVED: status.HTTP_403_FORBIDDEN,
    ErrorCode.MODEL_PROVIDER_UNAVAILABLE: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.RUNTIME_POLICY_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RUNTIME_APPROVAL_REQUIRED: status.HTTP_403_FORBIDDEN,
    ErrorCode.RUNTIME_APPROVAL_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.RUNTIME_BUDGET_EXCEEDED: status.HTTP_402_PAYMENT_REQUIRED,
    ErrorCode.RUNTIME_RATE_LIMITED: status.HTTP_429_TOO_MANY_REQUESTS,
    ErrorCode.RUNTIME_QUEUE_FULL: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.WORKER_UNAVAILABLE: status.HTTP_503_SERVICE_UNAVAILABLE,
    ErrorCode.ROLLBACK_NOT_AVAILABLE: status.HTTP_409_CONFLICT,
    ErrorCode.KILL_SWITCH_ACTIVE: status.HTTP_423_LOCKED,
    ErrorCode.SECRET_REFERENCE_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    # Enterprise Agent Registry (Phase 5.1 §68).
    ErrorCode.AGENT_ALREADY_EXISTS: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_SLUG_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_EXTERNAL_REFERENCE_CONFLICT: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_INVALID_STATUS: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_TRANSITION_NOT_ALLOWED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_NOT_EDITABLE: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_VALIDATION_FAILED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_VALIDATION_IN_PROGRESS: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_APPROVAL_REQUIRED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_ACTIVATION_BLOCKED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_OWNER_REQUIRED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_OWNER_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_OWNER_SCOPE_MISMATCH: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_IDENTITY_REQUIRED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_IDENTITY_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_IDENTITY_SCOPE_MISMATCH: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_IDENTITY_ALREADY_ASSIGNED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_DEFINITION_REQUIRED: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_ENTRYPOINT_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_INPUT_SCHEMA_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_OUTPUT_SCHEMA_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_CONFIGURATION_SCHEMA_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_RISK_CLASSIFICATION_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_DUPLICATE_CONFIRMED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_DUPLICATE_REVIEW_REQUIRED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_CONCURRENT_MODIFICATION: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_IMPORT_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_IMPORT_PARTIAL_FAILURE: status.HTTP_207_MULTI_STATUS,
    ErrorCode.AGENT_EXPORT_DENIED: status.HTTP_403_FORBIDDEN,
    ErrorCode.AGENT_VERSION_INVALID_SEMVER: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_VERSION_SEMVER_NOT_INCREASING: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_VERSION_SNAPSHOT_LOCKED: status.HTTP_409_CONFLICT,
    ErrorCode.AGENT_VERSION_ROLLBACK_TARGET_INVALID: status.HTTP_422_UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_RELEASE_CHANNEL_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.COMPATIBILITY_BASELINE_NOT_FOUND: status.HTTP_404_NOT_FOUND,
    ErrorCode.COMPATIBILITY_SNAPSHOT_UNAVAILABLE: status.HTTP_409_CONFLICT,
}


class IdentityError(Exception):
    """Raised by identity services/repositories; rendered as the error envelope.

    ``headers`` carries response headers the *error itself* demands — currently only
    ``Retry-After`` on a 429, which a client cannot behave correctly without.
    """

    def __init__(self, code: str, message: str, *, headers: dict[str, str] | None = None) -> None:
        self.code = code
        self.message = message
        self.headers = headers or {}
        self.http_status = _STATUS.get(code, status.HTTP_400_BAD_REQUEST)
        super().__init__(message)


def error_body(code: str, message: str, request_id: str | None) -> dict[str, object]:
    """The standard error envelope (SRS §5).

    ``meta`` mirrors the success envelope so both carry ``request_id`` + ``timestamp``.
    ``request_id`` is also kept at the top level for backward compatibility with the
    clients and tests that read it there.
    """
    return {
        "success": False,
        "error": {"code": code, "message": message},
        "request_id": request_id,
        "meta": {
            "request_id": request_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
    }


def _request_id(request: Request) -> str | None:
    # ``RequestContextMiddleware`` (app.core.middleware) sets ``state.request_id`` to
    # the supplied-or-generated id for every request, honouring the configured header
    # name. Prefer it; fall back to the raw header for any request that somehow
    # bypassed the middleware (e.g. a directly-constructed test request).
    return getattr(request.state, "request_id", None) or request.headers.get("x-request-id")


def register_identity_exception_handlers(app: FastAPI) -> None:
    """Register the identity error handler on the FastAPI app."""

    @app.exception_handler(IdentityError)
    async def _handle_identity_error(request: Request, exc: IdentityError) -> JSONResponse:
        return JSONResponse(
            status_code=exc.http_status,
            content=error_body(exc.code, exc.message, _request_id(request)),
            headers=exc.headers or None,
        )

    @app.exception_handler(PasswordPolicyError)
    async def _handle_password_policy_error(
        request: Request, exc: PasswordPolicyError
    ) -> JSONResponse:
        """A password-policy rejection is a client validation error, never a 500.

        Routes that set a password (legacy ``/auth/register``, ``/users``) call
        ``hash_user_password`` directly and let this handler shape the response.

        The exception carries a specific ``code`` (``PASSWORD_TOO_WEAK`` /
        ``PASSWORD_POLICY_FAILED``) so the client can react precisely (SRS §26).
        """
        code = getattr(exc, "code", None) or ErrorCode.PASSWORD_POLICY_FAILED
        return JSONResponse(
            status_code=422,
            content=error_body(code, str(exc), _request_id(request)),
        )
