import type { ApprovalDetail, ApprovalListItem } from '../types'

/** A representative queue row used across the approvals module tests. */
export const approvalRowFixture: ApprovalListItem = {
  id: 'a1b2c3d4-0000-0000-0000-000000000000',
  agent_action_id: 'act-1',
  requested_by_agent_id: 'agent-1',
  agent_name: 'BillingAgent',
  resource: 'CLAIM',
  action: 'SUBMIT_CLAIM',
  risk_score: 92,
  decision: 'PENDING',
  priority: 'CRITICAL',
  escalation_target: null,
  reviewer_name: null,
  assigned_to_name: null,
  sla_due_at: '2026-07-01T10:00:00Z',
  created_at: '2026-06-30T10:00:00Z',
  reviewed_at: null,
}

/** A full detail payload for workbench/detail tests. */
export const approvalDetailFixture: ApprovalDetail = {
  id: approvalRowFixture.id,
  organization_id: 'org',
  agent_action_id: 'act-1',
  requested_by_agent_id: 'agent-1',
  reviewed_by_user_id: null,
  assigned_to_user_id: null,
  decision: 'PENDING',
  priority: 'CRITICAL',
  review_comment: null,
  escalation_target: null,
  sla_due_at: '2026-07-01T10:00:00Z',
  escalated_at: null,
  created_at: '2026-06-30T10:00:00Z',
  reviewed_at: null,
  reviewer_name: null,
  assigned_to_name: null,
  agent: {
    id: 'agent-1',
    name: 'BillingAgent',
    version: '1.2.0',
    owner: 'Finance',
    department: 'Billing',
    status: 'ACTIVE',
    health: 'HEALTHY',
    last_activity: '2026-06-30T09:00:00Z',
  },
  action: {
    id: 'act-1',
    resource: 'CLAIM',
    action: 'SUBMIT_CLAIM',
    input_payload: { amount: 25000, patient_id: 'PT-9' },
    risk_score: 92,
    decision: 'PENDING_APPROVAL',
    decision_reason: "Matched policy 'Large Claim Approval'.",
    status: 'CREATED',
    created_at: '2026-06-30T10:00:00Z',
  },
  policy: {
    matched: true,
    policy_name: 'Large Claim Approval',
    decision: 'PENDING_APPROVAL',
    conditions: { amount_gt: 10000 },
    reason: "Matched policy 'Large Claim Approval' -> PENDING_APPROVAL.",
  },
  risk: {
    score: 92,
    action_score: 65,
    resource_score: 10,
    factors: { Action: 65, Resource: 10, Financial: 10, 'PHI Exposure': 20 },
    confidence: 91,
    recommendation: 'Human review required — critical risk.',
  },
  comments: [
    {
      id: 'c1',
      approval_id: approvalRowFixture.id,
      user_id: 'user-1',
      comment: 'Looks high risk, verifying documentation.',
      created_at: '2026-06-30T10:30:00Z',
    },
  ],
}
