"""Authorization enums (Phase 4.3.1 §8, §9, §15, §23)."""

from __future__ import annotations

import enum


class RoleCategory(str, enum.Enum):
    """§9 — what kind of role this is."""

    SYSTEM = "SYSTEM"
    CUSTOM = "CUSTOM"
    ORGANIZATION = "ORGANIZATION"
    PROJECT = "PROJECT"
    RESOURCE = "RESOURCE"


class RoleStatus(str, enum.Enum):
    """§8 — role lifecycle. DELETED is a terminal soft-delete; rows are never
    hard-removed while assignments or audit history reference them."""

    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    UPDATED = "UPDATED"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"
    DELETED = "DELETED"

    @property
    def is_assignable_state(self) -> bool:
        """A role can only receive new assignments while it is live."""
        return self in (RoleStatus.CREATED, RoleStatus.ACTIVE, RoleStatus.UPDATED)


class AssignmentScope(str, enum.Enum):
    """§15 — how far a role assignment reaches."""

    GLOBAL = "GLOBAL"
    ORGANIZATION = "ORGANIZATION"
    DEPARTMENT = "DEPARTMENT"
    TEAM = "TEAM"
    PROJECT = "PROJECT"
    RESOURCE = "RESOURCE"


class AuthorizationDecision(str, enum.Enum):
    """Recorded on every authorization-audit row for a permission check."""

    ALLOW = "ALLOW"
    DENY = "DENY"


class AuthorizationEngineEvent(str, enum.Enum):
    """The events the Permission Engine generates while evaluating a decision
    (Phase 4.3.2 §27). The two outcome events are persisted on the decision; the
    pipeline-step events are generated as a per-decision trace and surfaced on the
    ``/authorization/check`` response for observability."""

    AUTHORIZATION_GRANTED = "AUTHORIZATION_GRANTED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    PERMISSION_CACHE_REFRESHED = "PERMISSION_CACHE_REFRESHED"
    ROLE_RESOLVED = "ROLE_RESOLVED"
    WILDCARD_EXPANDED = "WILDCARD_EXPANDED"
    SCOPE_VALIDATED = "SCOPE_VALIDATED"
    CONFLICT_RESOLVED = "CONFLICT_RESOLVED"


class AuthorizationAuditEvent(str, enum.Enum):
    """§23 — the administrative change events this subsystem emits, plus the
    per-request decision event."""

    ROLE_CREATED = "ROLE_CREATED"
    ROLE_UPDATED = "ROLE_UPDATED"
    ROLE_ARCHIVED = "ROLE_ARCHIVED"
    ROLE_DELETED = "ROLE_DELETED"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_REMOVED = "ROLE_REMOVED"
    PERMISSION_CREATED = "PERMISSION_CREATED"
    PERMISSION_UPDATED = "PERMISSION_UPDATED"
    PERMISSION_DELETED = "PERMISSION_DELETED"
    PERMISSION_ASSIGNED = "PERMISSION_ASSIGNED"
    PERMISSION_REMOVED = "PERMISSION_REMOVED"
    ROLE_HIERARCHY_UPDATED = "ROLE_HIERARCHY_UPDATED"
    ROLE_HIERARCHY_REMOVED = "ROLE_HIERARCHY_REMOVED"
    AUTHORIZATION_DECISION = "AUTHORIZATION_DECISION"
    # Administration portal (Phase 4.3.7 §22).
    ACCESS_REVIEW_CREATED = "ACCESS_REVIEW_CREATED"
    ACCESS_REVIEW_ACTIVATED = "ACCESS_REVIEW_ACTIVATED"
    ACCESS_REVIEW_ITEM_DECIDED = "ACCESS_REVIEW_ITEM_DECIDED"
    ACCESS_REVIEW_COMPLETED = "ACCESS_REVIEW_COMPLETED"
    ACCESS_REVIEW_ARCHIVED = "ACCESS_REVIEW_ARCHIVED"
    SIMULATION_EXECUTED = "SIMULATION_EXECUTED"
    DECISION_VIEWED = "DECISION_VIEWED"
    AUDIT_EXPORTED = "AUDIT_EXPORTED"
    # Identity Governance & Administration (Phase 4.3.8 §23).
    CERTIFICATION_CREATED = "CERTIFICATION_CREATED"
    CERTIFICATION_COMPLETED = "CERTIFICATION_COMPLETED"
    ACCESS_APPROVED = "ACCESS_APPROVED"
    ACCESS_REVOKED = "ACCESS_REVOKED"
    SOD_RULE_CREATED = "SOD_RULE_CREATED"
    SOD_RULE_ACTIVATED = "SOD_RULE_ACTIVATED"
    SOD_VIOLATION_FOUND = "SOD_VIOLATION_FOUND"
    TOXIC_PERMISSION_FOUND = "TOXIC_PERMISSION_FOUND"
    ORPHANED_ACCOUNT_DETECTED = "ORPHANED_ACCOUNT_DETECTED"
    PRIVILEGED_REVIEW_COMPLETED = "PRIVILEGED_REVIEW_COMPLETED"
    GOVERNANCE_FINDING_RESOLVED = "GOVERNANCE_FINDING_RESOLVED"
    REMEDIATION_CREATED = "REMEDIATION_CREATED"
    REMEDIATION_EXECUTED = "REMEDIATION_EXECUTED"
    RISK_SCORE_COMPUTED = "RISK_SCORE_COMPUTED"
    COMPLIANCE_REPORT_GENERATED = "COMPLIANCE_REPORT_GENERATED"
    # Agent Runtime & Lifecycle Management (Phase 5.0 §76).
    RUNTIME_AGENT_REGISTERED = "RUNTIME_AGENT_REGISTERED"
    RUNTIME_AGENT_ACTIVATED = "RUNTIME_AGENT_ACTIVATED"
    RUNTIME_AGENT_SUSPENDED = "RUNTIME_AGENT_SUSPENDED"
    RUNTIME_AGENT_ARCHIVED = "RUNTIME_AGENT_ARCHIVED"
    RUNTIME_AGENT_RETIRED = "RUNTIME_AGENT_RETIRED"
    RUNTIME_VERSION_CREATED = "RUNTIME_VERSION_CREATED"
    RUNTIME_VERSION_PUBLISHED = "RUNTIME_VERSION_PUBLISHED"
    RUNTIME_VERSION_DEPRECATED = "RUNTIME_VERSION_DEPRECATED"
    RUNTIME_VERSION_REVOKED = "RUNTIME_VERSION_REVOKED"
    RUNTIME_DEPLOYMENT_CREATED = "RUNTIME_DEPLOYMENT_CREATED"
    RUNTIME_DEPLOYMENT_ACTIVE = "RUNTIME_DEPLOYMENT_ACTIVE"
    RUNTIME_DEPLOYMENT_FAILED = "RUNTIME_DEPLOYMENT_FAILED"
    RUNTIME_DEPLOYMENT_SUSPENDED = "RUNTIME_DEPLOYMENT_SUSPENDED"
    RUNTIME_DEPLOYMENT_ROLLED_BACK = "RUNTIME_DEPLOYMENT_ROLLED_BACK"
    RUNTIME_DEPLOYMENT_RETIRED = "RUNTIME_DEPLOYMENT_RETIRED"
    RUNTIME_EXECUTION_CREATED = "RUNTIME_EXECUTION_CREATED"
    RUNTIME_EXECUTION_DENIED = "RUNTIME_EXECUTION_DENIED"
    RUNTIME_EXECUTION_APPROVAL_REQUIRED = "RUNTIME_EXECUTION_APPROVAL_REQUIRED"
    RUNTIME_EXECUTION_SUCCEEDED = "RUNTIME_EXECUTION_SUCCEEDED"
    RUNTIME_EXECUTION_FAILED = "RUNTIME_EXECUTION_FAILED"
    RUNTIME_EXECUTION_CANCELLED = "RUNTIME_EXECUTION_CANCELLED"
    RUNTIME_EXECUTION_DEAD_LETTERED = "RUNTIME_EXECUTION_DEAD_LETTERED"
    RUNTIME_CAPABILITY_ASSIGNED = "RUNTIME_CAPABILITY_ASSIGNED"
    RUNTIME_CAPABILITY_REVOKED = "RUNTIME_CAPABILITY_REVOKED"
    RUNTIME_TOOL_ASSIGNED = "RUNTIME_TOOL_ASSIGNED"
    RUNTIME_TOOL_REVOKED = "RUNTIME_TOOL_REVOKED"
    RUNTIME_TOOL_CALL_DENIED = "RUNTIME_TOOL_CALL_DENIED"
    RUNTIME_LIMIT_EXCEEDED = "RUNTIME_LIMIT_EXCEEDED"
    RUNTIME_KILL_SWITCH_ACTIVATED = "RUNTIME_KILL_SWITCH_ACTIVATED"
    RUNTIME_ROLLBACK_COMPLETED = "RUNTIME_ROLLBACK_COMPLETED"
