// Identity Governance & Administration (Phase 4.3.8).
export { GovernanceDashboardPage } from './GovernanceDashboardPage'
export { CertificationCampaignsPage } from './CertificationCampaignsPage'
export { CertificationReviewPage } from './CertificationReviewPage'
export { SoDRulesPage } from './SoDRulesPage'
export { SoDFindingsPage } from './SoDFindingsPage'
export { ToxicPermissionsPage } from './ToxicPermissionsPage'
export { PrivilegedAccessPage } from './PrivilegedAccessPage'
export { OrphanedAccountsPage } from './OrphanedAccountsPage'
export { GovernanceFindingsPage } from './GovernanceFindingsPage'
export { RemediationCenterPage } from './RemediationCenterPage'
export { ComplianceReportsPage } from './ComplianceReportsPage'
export { GovernanceAnalyticsPage } from './GovernanceAnalyticsPage'
export { GovernanceNav } from './components/GovernanceNav'
